# Generated by Django 2.2.3 on 2019-08-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp_name', to='users.UserGroup')),
                ('userref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
