# Generated by Django 2.2.3 on 2019-08-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='gender',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
