# Generated by Django 2.2.3 on 2019-10-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191006_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CART', 'cart'), ('ORDERED', 'ordered'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('SOLD', 'sold'), ('PAUSE', 'pause')], default=1, max_length=10),
        ),
    ]
