# Generated by Django 2.2.3 on 2019-09-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userextend_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='group_name',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
