# Generated by Django 2.2.3 on 2019-09-13 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190912_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='pics/MenuImage')),
                ('item_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='users.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='VegOrNonVeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics/VegOrNonVegImage')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_image', models.ImageField(upload_to='pics/ShopImage')),
                ('shop_description', models.CharField(max_length=50)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shop_size', models.CharField(max_length=25)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.IntegerField()),
                ('order_status', models.CharField(max_length=15)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_paystatus', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='users.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='item_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_shop', to='users.Shop'),
        ),
        migrations.AddField(
            model_name='menu',
            name='item_vegornonveg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_vegornonveg', to='users.VegOrNonVeg'),
        ),
    ]
