# Generated by Django 2.2.3 on 2019-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191006_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='acceptance',
            field=models.CharField(choices=[('ACCEPT', 'accept'), ('DENY', 'deny')], default='ACCEPT', max_length=10),
        ),
    ]
