# Generated by Django 2.2.3 on 2019-10-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userextend_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_image',
            field=models.ImageField(default=None, upload_to='pics/MenuImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='menu_name',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_vendor',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='purchasedate',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_shop', to='users.Shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='users.Menu'),
        ),
    ]
