# Generated by Django 2.2.3 on 2019-09-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190915_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_paystatus',
        ),
    ]
