# Generated by Django 2.2.3 on 2019-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
