# Generated by Django 2.2.3 on 2019-10-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_order_purchasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_state',
            field=models.CharField(blank=True, choices=[('PAUSE', 'pause'), ('START', 'start')], default='PAUSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'available'), ('SOLD', 'sold'), ('PAUSE', 'pause'), ('START', 'start')], default='AVAILABLE', max_length=10, null=True),
        ),
    ]
