# Generated by Django 2.2.3 on 2019-09-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190925_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderAndItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitemnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orderid', to='users.Order')),
                ('ordernum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderHistory', to='users.OrderHistory')),
            ],
        ),
    ]
