# Generated by Django 2.2.3 on 2019-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191006_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CART', 'cart'), ('ORDERED', 'ordered'), ('DELIVERED', 'delivered'), ('CANCELLED', 'cancelled')], max_length=10),
        ),
    ]
