# Generated by Django 2.2.3 on 2019-10-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191006_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_state',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('REMOVED', 'removed')], default='AVAILABLE', max_length=10),
        ),
    ]
